import { Metadata, NextPage } from 'next';
import React from 'react';
import teste from "../../../public/monocle.gif"
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'teste teste',
  description: 'Generated by create next app',
};

const Intruder: NextPage = () => {
  return (
    <>
		  <Link rel="icon" type="image/x-icon" href="../../../public/monocle.gif" />
      <div>Intruder</div>
			<div>Intruder2</div>
    </>
  );
};

export default Intruder