import { Metadata, NextPage } from 'next';
import React from 'react';

export const metadata: Metadata = {
  title: 'teste teste',
  description: 'Generated by create next app',
};

const Intruder: NextPage = () => {
  return (
    <>
      <div>Intruder</div>
			<div>Intruder2</div>
    </>
  );
};

export default Intruder